behaviors:
  #Тут пишутся гиперпараметры для обучения
  Walker: # Имя поведения которое мы учим (Из компоненты  Behavior Parameters - Behavior Name)
    trainer_type: ppo # Название алгоритма обучения
    hyperparameters: # гиперпараметры
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings: # гиперпараметры сети. нормализация, слои, скрытые размеры итп
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals: # гиперпараметры для награды (дискаунт фактор например для q значений)
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5 # сколько последних чекпоинтов обучения хранится
    max_steps: 10000000 # сколько шагов агент обучается
    time_horizon: 1000
    summary_freq: 30000
    threaded: true # многопоточность
